ci:
  autoupdate_schedule: "monthly" # Like dependabot
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autoupdate_branch: "develop"
  autofix_prs: false # Comment "pre-commit.ci autofix" on a PR to trigger

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Validate format
      - id: check-yaml
      - id: check-toml
      - id: check-json
      # Check for common mistakes
      - id: check-added-large-files
      - id: check-case-conflict
      # - id: check-illegal-windows-names # TODO: Enable in next release
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: mixed-line-ending
      - id: no-commit-to-branch # protects `main` by default
      - id: debug-statements
      - id: trailing-whitespace
        exclude: tests(/\w*)*/functional/t/trailing_whitespaces.py|tests/pyreverse/data/.*.html|doc/data/messages/t/trailing-whitespace/bad.py
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            tests(/\w*)*/functional/m/missing/missing_final_newline.py|
            tests/functional/t/trailing_newlines.py|
            doc/data/messages/t/trailing-newlines/bad.py|
          )$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black-jupyter

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
